package iso8583

var (
	mandatoryFields = map[string]string{
		"O":  "Optional.",
		"M":  "Mandatory.",
		"ME": "Mandatory echo. Shall echo the same data as the original message.",
		"00": "Reserved for ISO use.",
		"01": "Mandatory if fees affect reconciliation.",
		"02": "Mandatory if information is available and not read electronically from the card, e.g. manual card entry.",
		"03": "Mandatory, shall contain the same data as the original authorization (1xx) or financial presentment (2xx) message.",
		"04": "Mandatory if Amount cardholder billing or Amount cardholder billing fee is present.",
		"05": "Mandatory when the reconciliation and transaction currencies differ and this data element were not provided in the request or advice message.",
		"06": "Mandatory if track data is captured at the point of service.",
		"07": "Mandatory if the Primary account number conforms to International Standard ISO 7812.",
		"08": "Mandatory in a replacement, previously authorised, retrieval, representment, partial reversal or partial chargeback. Mandatory in a supplementary authorization, if available.",
		"09": "Reserved for ISO use.",
		"10": "Mandatory when the forwarding institution is not the same as the institution originating the message.",
		"11": "Reserved for ISO use.",
		"12": "Mandatory if transaction affects reconciliation and this data element was not provided in the request or advice message.",
		"13": "Mandatory if the reconciliation is not in balance. Contains the value calculated by the institution sending the reconciliation advice response. ",
		"14": "Mandatory if the transaction affects reconciliation and checkpoint reconciliation is used and this data element was not provided in the request or advice message.",
		"15": "Mandatory if available.",
		"16": "Mandatory in a response message if the data element was present in the original request or advice message. If present, it shall contain the same data as the original message.",
		"17": "Mandatory in the advice/notification if the data element was present in the original authorization/financial presentment request/advice notification message. If present, it shall contain the same data as the original message.",
		"18": "Mandatory if the approval code is required to be less than six characters. ",
		"19": "Mandatory when the receiving institution is not the same as the final destination of the message.",
		"20": "Mandatory when the institution that processed (approved or denied) an authorization or financial presentment is not the same institution identified in the primary account number.",
		"21": "Mandatory if a partial approval, declined or rejected transaction.",
		"22": "Mandatory if different from Date and time local transaction.",
		"23": "Mandatory if transaction affects reconciliation and checkpoint reconciliation used.",
		"24": "Mandatory if this message is used for cutover or checkpoint reconciliation.",
		"25": "Mandatory if this message is used for checkpoint reconciliation.",
		"26": "Mandatory for all processing codes except for inquiry services, i.e. processing code 3xxx.",
		"27": "Mandatory, shall echo the first two positions of the processing code in the original message.",
		"28": "Mandatory if function code indicates card administration.",
		"29": "Mandatory if function code is other than card administration.",
		"30": "Mandatory in real time transactions.",
		"31": "Mandatory if approved.",
		"32": "Mandatory if batch/file transfer control data elements do not uniquely identify the file to be loaded.",
		"33": "Mandatory once assigned, in all subsequent messages in this transaction (e.g. responses, acknowledgements, advices, notifications and instructions) and all messages in related transactions (e.g. financial presentments, chargebacks, reversals and retrievals). Shall contain the same value as original assigned.",
		"34": "Mandatory if fee collection is relevant to the life cycle of the transaction.",
		"35": "Mandatory in a network management message when Function code indicates a key is being delivered.",
		"36": "Mandatory in request response/advice response messages if the receiver detects an error in the request/repeat or advice/repeat messages.",
		"37": "Mandatory in the error notification message if present in the messages that contained the error condition, if the receiver can parse that message.",
		"38": "Mandatory in network management messages that denotes the start or end of a file transfer.",
		"39": "Mandatory in messages which are submitted as part of a batch or file transfer.",
		"40": "Mandatory in retrieval, chargeback and fee collection messages if provided in an original financial presentment. Shall contain the same values as used in the original transaction.",
		"41": "Mandatory if Function code is not 650 or 651.",
		"42": "Mandatory when the transaction is an accumulation transaction and the value applies to all transactions within the accumulated total.",
		"43": "Mandatory if Function code is 11",
		"44": "Mandatory if verification involves PAN",
		"45": "Mandatory if Function code is 109, 110, 112, or 113",
	}
)
